### ISSUE TITLE
Abrupt jump during transition from Dashboard -> My Accounts

### ISSUE THREAD

**Issue by harry14** [CRUx-BPHC/fest-manager#120]
All icons and text below 'My Account' text jump down abruptly when opening 'My Account' page after 'Dashboard' page.

**Comment by aero31aero** [comment]
The page transitions lag because the renderer has to do a lot of calculations to render two pages at the same time, and animate them. This won't show up on pages with a few elements but is easily observable on pages with more than a couple of elements.

TODO replace the transition with something simpler for the browser to handle.

**Comment by praneetmehta** [comment]
is this issue already closed because i dont see anything like that @aero31aero ?

**Comment by aero31aero** [comment]
Try it on a laptop with a weaker processor. The issue was to do with having a relatively complex transition between pages.

**Comment by rogeredthat** [comment]
Fixed recently. Closing this issue.
